Update nut-influxdb-exporter.py
Update the convert function to just try casting to float - InfluxDB assumes a float by default, and further I have used multiple NUT instances where some are an INT others a FLOAT causing casting error because InfluxDBClient specifically supplies 'i' in the write function for INTs.

It should resolve errors such as this:
influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write: field type conflict: input field \"input.voltage\" on measurement \"ups_status\" is type integer, already exists as type float dropped=1"}